import copyStateFrom from 'helpers/copyStateFrom';
import { makeAutoObservable } from 'mobx';

const initialState = {};

export const storiesStore = makeAutoObservable({
  mockData: {
    status: 'OK',
    copyright: 'Copyright (c) 2022 The New York Times Company. All Rights Reserved.',
    section: 'Arts',
    last_updated: '2022-06-02T10:07:37-04:00',
    num_results: 38,
    results: [
      {
        section: 'arts',
        subsection: 'television',
        title: '‘The Wire’ Stands Alone',
        abstract:
          'After 20 years, the classic drama is much praised and rarely imitated. For a series based on the idea that institutions don’t change, that’s fitting.',
        url: 'https://www.nytimes.com/2022/06/02/arts/television/the-wire-20th-anniversary.html',
        uri: 'nyt://article/f87205b4-2c26-5fdf-9de0-3ed882234623',
        byline: 'By James Poniewozik',
        item_type: 'Article',
        updated_date: '2022-06-02T05:00:24-04:00',
        created_date: '2022-06-02T05:00:24-04:00',
        published_date: '2022-06-02T05:00:24-04:00',
        material_type_facet: '',
        kicker: 'Critic’s Notebook',
        des_facet: ['Television', 'The Wire (TV Program)'],
        org_facet: ['Home Box Office'],
        per_facet: ['Simon, David (1960- )', 'Burns, Ed'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/05/24/arts/00wire-notebook/00wire-notebook-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1635,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Chase Hall for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/24/arts/00wire-notebook/00wire-notebook-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Chase Hall for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/24/arts/00wire-notebook/00wire-notebook-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Chase Hall for The New York Times',
          },
        ],
        short_url: 'https://nyti.ms/3xad8cI',
      },
      {
        section: 'arts',
        subsection: 'dance',
        title: '‘MJ’: Dancing the Pain, and Dancing the Pain Away',
        abstract:
          'What is the role of choreography on Broadway? Two musicals, “MJ” and “A Strange Loop,” shed light on the dancing body.',
        url: 'https://www.nytimes.com/2022/06/02/arts/dance/michael-jackson-mj-dancing.html',
        uri: 'nyt://article/f1a194c8-259a-558f-b9a3-bb160a3f384e',
        byline: 'By Gia Kourlas',
        item_type: 'Article',
        updated_date: '2022-06-02T09:00:16-04:00',
        created_date: '2022-06-02T09:00:16-04:00',
        published_date: '2022-06-02T09:00:16-04:00',
        material_type_facet: '',
        kicker: 'Critic’s Notebook',
        des_facet: [
          'Dancing',
          'Tony Awards (Theater Awards)',
          'A Strange Loop (Play)',
          'MJ (Play)',
        ],
        org_facet: [],
        per_facet: [
          'Jackson, Michael',
          'Jackson, Michael R',
          'Kelly, Raja Feather',
          'Wheeldon, Christopher',
        ],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/05/29/arts/29mj-dancer-2/merlin_198901542_0b8dadc5-bd9b-4ce4-b52a-f477f2608abb-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1328,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: 'Armored: Myles Frost as Michael Jackson in the musical “MJ.”',
            copyright: 'Sara Krulwich/The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/29/arts/29mj-dancer-2/merlin_198901542_0b8dadc5-bd9b-4ce4-b52a-f477f2608abb-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'Armored: Myles Frost as Michael Jackson in the musical “MJ.”',
            copyright: 'Sara Krulwich/The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/29/arts/29mj-dancer-2/merlin_198901542_0b8dadc5-bd9b-4ce4-b52a-f477f2608abb-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'Armored: Myles Frost as Michael Jackson in the musical “MJ.”',
            copyright: 'Sara Krulwich/The New York Times',
          },
        ],
        short_url: 'https://nyti.ms/3aldsMA',
      },
      {
        section: 'movies',
        subsection: '',
        title: 'Are the Movies Liberal?',
        abstract:
          'Everyone knows Hollywood is progressive. But look at the films it churns out. They tell another story.',
        url: 'https://www.nytimes.com/2022/06/02/movies/liberal-hollywood-dog.html',
        uri: 'nyt://article/19b6fe2e-c63e-5641-ab22-c32cede069fd',
        byline: 'By A.O. Scott',
        item_type: 'Article',
        updated_date: '2022-06-02T09:08:28-04:00',
        created_date: '2022-06-02T05:00:28-04:00',
        published_date: '2022-06-02T05:00:28-04:00',
        material_type_facet: '',
        kicker: "Critic's Notebook",
        des_facet: [
          'Movies',
          'First Blood (Movie)',
          'Top Gun: Maverick (Movie)',
          'Dog (Movie)',
          'Conservatism (US Politics)',
          'The Batman (Movie)',
          'Liberalism (US Politics)',
        ],
        org_facet: [],
        per_facet: [],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/arts/05LiberalNotebook-illo/05LiberalNotebook-illo-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1369,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Matt Chinworth',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/arts/05LiberalNotebook-illo/05LiberalNotebook-illo-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Matt Chinworth',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/arts/05LiberalNotebook-illo/05LiberalNotebook-illo-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Matt Chinworth',
          },
        ],
        short_url: 'https://nyti.ms/3aipczN',
      },
      {
        section: 'arts',
        subsection: '',
        title: 'Johnny Depp Jury Finds That Amber Heard Defamed Him in Op-Ed',
        abstract:
          'The jury in Virginia found that Ms. Heard had damaged her ex-husband’s reputation with an op-ed in which she identified herself as a “public figure representing domestic abuse.”',
        url: 'https://www.nytimes.com/2022/06/01/arts/depp-heard-trial.html',
        uri: 'nyt://article/ccd85849-ea35-5a87-98d1-e5ad2e0d8e62',
        byline: 'By Julia Jacobs and Adam Bednar',
        item_type: 'Article',
        updated_date: '2022-06-02T10:03:51-04:00',
        created_date: '2022-06-01T19:19:32-04:00',
        published_date: '2022-06-01T19:19:32-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: [
          'Libel and Slander',
          'Suits and Litigation (Civil)',
          'Decisions and Verdicts',
          'Domestic Violence',
          'Compensation for Damages (Law)',
        ],
        org_facet: [],
        per_facet: ['Depp, Johnny', 'Heard, Amber'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/05/31/multimedia/31depp-1/31depp-1-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1434,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'The libel case that pitted Johnny Depp against his ex-wife Amber Heard lasted six weeks.',
            copyright: 'Photographs by Steve Helber/Associated Press',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/31/multimedia/31depp-1/31depp-1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'The libel case that pitted Johnny Depp against his ex-wife Amber Heard lasted six weeks.',
            copyright: 'Photographs by Steve Helber/Associated Press',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/31/multimedia/31depp-1/31depp-1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'The libel case that pitted Johnny Depp against his ex-wife Amber Heard lasted six weeks.',
            copyright: 'Photographs by Steve Helber/Associated Press',
          },
        ],
        short_url: 'https://nyti.ms/3t5wnBR',
      },
      {
        section: 'arts',
        subsection: 'television',
        title: 'Bill Cosby Accused at Trial of Assaulting Judy Huth as Teenager',
        abstract:
          'The trial stemming from Ms. Huth’s lawsuit, which says Mr. Cosby sexually assaulted her when she was a minor, began in Los Angeles as her lawyers described what she says occurred in the Playboy Mansion.',
        url: 'https://www.nytimes.com/2022/06/01/arts/television/opening-statements-bill-cosby-judy-huth-civil-trial.html',
        uri: 'nyt://article/a198bc66-fabf-5878-bfcf-a4698ad28cad',
        byline: 'By Graham Bowley, Lauren Herstik and Douglas Morino',
        item_type: 'Article',
        updated_date: '2022-06-01T23:17:12-04:00',
        created_date: '2022-06-01T18:05:11-04:00',
        published_date: '2022-06-01T18:05:11-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Suits and Litigation (Civil)', 'Sex Crimes'],
        org_facet: [],
        per_facet: ['Cosby, Bill', 'Huth, Judy (1959- )', 'Constand, Andrea'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/multimedia/01cosby-1/01cosby-1-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1332,
            width: 1873,
            type: 'image',
            subtype: 'photo',
            caption:
              'Judy Huth will testify in support of her sexual assault lawsuit. Bill Cosby has decided not to appear, according to his spokesman.',
            copyright: 'Lucy Nicholson/Reuters',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/multimedia/01cosby-1/01cosby-1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Judy Huth will testify in support of her sexual assault lawsuit. Bill Cosby has decided not to appear, according to his spokesman.',
            copyright: 'Lucy Nicholson/Reuters',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/multimedia/01cosby-1/01cosby-1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Judy Huth will testify in support of her sexual assault lawsuit. Bill Cosby has decided not to appear, according to his spokesman.',
            copyright: 'Lucy Nicholson/Reuters',
          },
        ],
        short_url: 'https://nyti.ms/3PY5x8A',
      },
      {
        section: 'arts',
        subsection: 'music',
        title: 'Diamanda Galás Gives Voice to Unbearable Pain, Once More',
        abstract:
          'Revisiting “The Divine Punishment,” the first album in a trilogy addressing AIDS, and at work on new music, the singer and composer is still exploring isolation in her singular, startling way.',
        url: 'https://www.nytimes.com/2022/06/02/arts/music/diamanda-galas-divine-punishment.html',
        uri: 'nyt://article/d2fcb0ac-affb-5b4a-8452-638d05fef8d8',
        byline: 'By Zachary Woolfe',
        item_type: 'Article',
        updated_date: '2022-06-02T10:00:10-04:00',
        created_date: '2022-06-02T10:00:10-04:00',
        published_date: '2022-06-02T10:00:10-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: [
          'Music',
          'The Divine Punishment (Album)',
          'Content Type: Personal Profile',
          'Acquired Immune Deficiency Syndrome',
          'Broken Gargoyles (Album)',
          'Women and Girls',
        ],
        org_facet: [],
        per_facet: ['Galas, Diamanda'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/arts/05DIAMANDA1/merlin_207460866_78da01c5-0ec8-43fb-8afa-9ab77ecd402f-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 2048,
            width: 1366,
            type: 'image',
            subtype: 'photo',
            caption:
              'A remastered version of Diamanda Galás’s “The Divine Punishment” is out on June 10, in all its blistering glory. Her next record, “Broken Gargoyles,” will arrive in August.',
            copyright: 'Michael Tyrone Delaney for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/arts/05DIAMANDA1/05DIAMANDA1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'A remastered version of Diamanda Galás’s “The Divine Punishment” is out on June 10, in all its blistering glory. Her next record, “Broken Gargoyles,” will arrive in August.',
            copyright: 'Michael Tyrone Delaney for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/arts/05DIAMANDA1/05DIAMANDA1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'A remastered version of Diamanda Galás’s “The Divine Punishment” is out on June 10, in all its blistering glory. Her next record, “Broken Gargoyles,” will arrive in August.',
            copyright: 'Michael Tyrone Delaney for The New York Times',
          },
        ],
        short_url: 'https://nyti.ms/3x2IAZc',
      },
      {
        section: 'theater',
        subsection: '',
        title: '‘Almost Famous,’ Now a Musical, Will Open on Broadway This Fall',
        abstract:
          'The stage adaptation, with book and lyrics by Cameron Crowe and music and lyrics by Tom Kitt, will begin previews Sept. 13.',
        url: 'https://www.nytimes.com/2022/06/02/theater/almost-famous-broadway.html',
        uri: 'nyt://article/d0463f86-436a-5287-a7cb-96d19d5f6582',
        byline: 'By Michael Paulson',
        item_type: 'Article',
        updated_date: '2022-06-02T10:00:10-04:00',
        created_date: '2022-06-02T10:00:10-04:00',
        published_date: '2022-06-02T10:00:10-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Theater', 'Music', 'Movies', 'Almost Famous (Play)'],
        org_facet: ['Old Globe Theater Co'],
        per_facet: [
          'Crowe, Cameron',
          'Herrin, Jeremy',
          'Kitt, Tom',
          'Vollack, Lia',
          'Pfeiffer, Solea',
        ],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02almost-famous/02almost-famous-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1518,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'The San Diego ensemble of “Almost Famous” (including returning cast members Solea Pfeiffer and Casey Likes, hugging, center) during its initial run in 2019 at the Old Globe Theater there.',
            copyright: 'Bruce Glikas/WireImage, via Getty Images',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02almost-famous/02almost-famous-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'The San Diego ensemble of “Almost Famous” (including returning cast members Solea Pfeiffer and Casey Likes, hugging, center) during its initial run in 2019 at the Old Globe Theater there.',
            copyright: 'Bruce Glikas/WireImage, via Getty Images',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02almost-famous/02almost-famous-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'The San Diego ensemble of “Almost Famous” (including returning cast members Solea Pfeiffer and Casey Likes, hugging, center) during its initial run in 2019 at the Old Globe Theater there.',
            copyright: 'Bruce Glikas/WireImage, via Getty Images',
          },
        ],
        short_url: 'https://nyti.ms/3t7UqQn',
      },
      {
        section: 'arts',
        subsection: 'television',
        title: 'A British TV Show Finds Dark Humor on the Maternity Ward',
        abstract:
          '“This Is Going to Hurt,” a dramedy starring Ben Whishaw, kindled debate in Britain about hospital care for pregnant women and the pressures on doctors.',
        url: 'https://www.nytimes.com/2022/06/02/arts/television/this-is-going-to-hurt.html',
        uri: 'nyt://article/74ec0cf2-a491-53c2-bb6a-bd6bc6b22426',
        byline: '',
        item_type: 'Article',
        updated_date: '2022-06-02T09:22:35-04:00',
        created_date: '2022-06-02T09:22:35-04:00',
        published_date: '2022-06-02T09:22:35-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: [
          'Television',
          'Books and Literature',
          'Doctors',
          'Pregnancy and Childbirth',
          'This is Going to Hurt: Secret Diaries of a Junior Doctor (Book)',
        ],
        org_facet: ['National Health Service'],
        per_facet: ['Adam Kay', 'Whishaw, Ben', 'Ambika Mod'],
        geo_facet: ['Great Britain'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02hurt5/merlin_205806288_57b7d9de-a80d-4232-a33e-20cd45bc0992-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1151,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Anika Molna/AMC',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02hurt5/02hurt5-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Anika Molna/AMC',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02hurt5/02hurt5-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Anika Molna/AMC',
          },
        ],
        short_url: 'https://nyti.ms/3x5QgK2',
      },
      {
        section: 'arts',
        subsection: 'television',
        title: 'Does a Comedian Really Need an Audience?',
        abstract:
          'Filmed during lockdown, a new Netflix special from Norm Macdonald and outtakes from Bo Burnham’s “Inside” suggest that crowd laughter can be limiting.',
        url: 'https://www.nytimes.com/2022/06/01/arts/television/bo-burnham-norm-macdonald-comedy.html',
        uri: 'nyt://article/76823698-9afc-5565-96e4-6aaa0b76e3b9',
        byline: 'By Jason Zinoman',
        item_type: 'Article',
        updated_date: '2022-06-01T22:07:07-04:00',
        created_date: '2022-06-01T13:39:38-04:00',
        published_date: '2022-06-01T13:39:38-04:00',
        material_type_facet: '',
        kicker: 'On comedy',
        des_facet: [
          'Comedy and Humor',
          'Inside (TV Program)',
          'Nothing Special (TV Program)',
          'Television',
        ],
        org_facet: ['Netflix Inc', 'YouTube.com'],
        per_facet: ['Burnham, Bo (1990- )', 'Macdonald, Norm'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/01comedy-burnham2-norm/merlin_207858237_8c2f3538-49cc-44bb-a9c8-f58269a81f51-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1067,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'Norm Macdonald made Netflix’s “Nothing Special” in his home during lockdown in 2020; he died last year.',
            copyright: 'Netflix',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/01comedy-burnham2-norm/01comedy-burnham2-norm-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Norm Macdonald made Netflix’s “Nothing Special” in his home during lockdown in 2020; he died last year.',
            copyright: 'Netflix',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/01comedy-burnham2-norm/01comedy-burnham2-norm-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Norm Macdonald made Netflix’s “Nothing Special” in his home during lockdown in 2020; he died last year.',
            copyright: 'Netflix',
          },
        ],
        short_url: 'https://nyti.ms/3t9mPWw',
      },
      {
        section: 'arts',
        subsection: '',
        title: 'Spider-Man Turns 60 Years Old This Month. He’s as Boyish as Ever.',
        abstract:
          'Before movie franchises, Peter Parker (and his alter ego) began in the humble pages of comic books. To look back, we asked readers for some of their favorite adventures.',
        url: 'https://www.nytimes.com/2022/06/01/arts/spider-man-60.html',
        uri: 'nyt://article/de5c0d98-115a-5b60-b02e-a3c69a45528c',
        byline: 'By George Gene Gustines',
        item_type: 'Article',
        updated_date: '2022-06-01T22:13:44-04:00',
        created_date: '2022-06-01T10:41:13-04:00',
        published_date: '2022-06-01T10:41:13-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Spider-Man (Fictional Character)', 'Comic Books and Strips'],
        org_facet: ['Marvel Entertainment'],
        per_facet: ['Lee, Stan', 'Zdarsky, Chip', 'Ditko, Steve', 'Bendis, Brian Michael'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/00spiderman-Fantasy15/00spiderman-Fantasy15-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 2048,
            width: 1333,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Marvel Entertainment',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/00spiderman-Fantasy15/00spiderman-Fantasy15-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Marvel Entertainment',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/00spiderman-Fantasy15/00spiderman-Fantasy15-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Marvel Entertainment',
          },
        ],
        short_url: 'https://nyti.ms/3GG1BoH',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'Trying to Contain William Klein in One Show Isn’t Easy',
        abstract:
          'An I.C.P. retrospective displays the groundbreaking exuberance and tabloid punch of a master photographer.',
        url: 'https://www.nytimes.com/2022/06/02/arts/design/william-klein-photography-icp-review.html',
        uri: 'nyt://article/05a7b8d2-4ebc-51b6-bddf-f35d67d10d90',
        byline: 'By Arthur Lubow',
        item_type: 'Article',
        updated_date: '2022-06-02T08:52:48-04:00',
        created_date: '2022-06-02T08:52:48-04:00',
        published_date: '2022-06-02T08:52:48-04:00',
        material_type_facet: '',
        kicker: 'Critic’s PIck',
        des_facet: ['Art', 'Photography', 'Movies'],
        org_facet: [
          'International Center for Photography',
          'International Center of Photography',
          'Vogue',
        ],
        per_facet: ['Frank, Robert', 'Little Richard'],
        geo_facet: ['Paris (France)', 'Russia'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02klein-ICP-review-2/merlin_207832749_27633440-d2b9-4741-8c80-313258356228-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1478,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'William Klein, “Bikini, Moskva (River), Moscow,” 1959. With his wide-angle lens, an elderly onlooker and an exuberant sunbather, Klein turned a park into a theatrical stage. ',
            copyright: 'William Klein and Howard Greenberg Gallery',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02klein-ICP-review-2/merlin_207832749_27633440-d2b9-4741-8c80-313258356228-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'William Klein, “Bikini, Moskva (River), Moscow,” 1959. With his wide-angle lens, an elderly onlooker and an exuberant sunbather, Klein turned a park into a theatrical stage. ',
            copyright: 'William Klein and Howard Greenberg Gallery',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02klein-ICP-review-2/02klein-ICP-review-2-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'William Klein, “Bikini, Moskva (River), Moscow,” 1959. With his wide-angle lens, an elderly onlooker and an exuberant sunbather, Klein turned a park into a theatrical stage. ',
            copyright: 'William Klein and Howard Greenberg Gallery',
          },
        ],
        short_url: 'https://nyti.ms/3tcnE0z',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘Fire Island’ Review: Oh, the Summer Nights',
        abstract:
          'The quips are almost as hot as the sexual tension in Andrew Ahn and Joel Kim Booster’s loosely paced but endearing romantic comedy.',
        url: 'https://www.nytimes.com/2022/06/02/movies/fire-island-review.html',
        uri: 'nyt://article/3ed832cc-3522-5e5d-9e63-1ec90aebb4e6',
        byline: 'By Elisabeth Vincentelli',
        item_type: 'Article',
        updated_date: '2022-06-02T07:00:03-04:00',
        created_date: '2022-06-02T07:00:03-04:00',
        published_date: '2022-06-02T07:00:03-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Movies', 'Fire Island (Movie)'],
        org_facet: [],
        per_facet: [
          'Booster, Joel Kim (Comedian)',
          'Yang, Bowen (1990- )',
          'Ahn, Andrew (Film Director)',
        ],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/fireisland1/fireisland1-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1163,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'From left, Margaret Cho, Tomas Matos, Bowen Yang, Joel Kim Booster and Matt Rogers in “Fire Island.”',
            copyright: 'Jeong Park/Searchlight Pictures/20th Century Studios/Hulu',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/fireisland1/fireisland1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'From left, Margaret Cho, Tomas Matos, Bowen Yang, Joel Kim Booster and Matt Rogers in “Fire Island.”',
            copyright: 'Jeong Park/Searchlight Pictures/20th Century Studios/Hulu',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/fireisland1/fireisland1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'From left, Margaret Cho, Tomas Matos, Bowen Yang, Joel Kim Booster and Matt Rogers in “Fire Island.”',
            copyright: 'Jeong Park/Searchlight Pictures/20th Century Studios/Hulu',
          },
        ],
        short_url: 'https://nyti.ms/3xaDVpp',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘Benediction’ Review: A Poet’s Life, in Love and War',
        abstract:
          'Terence Davies’s latest film is a biography of Siegfried Sassoon, whose writing about World War I changed British literature.',
        url: 'https://www.nytimes.com/2022/06/02/movies/benediction-review.html',
        uri: 'nyt://article/b3222139-962f-5d68-af7d-85c3dff21366',
        byline: 'By A.O. Scott',
        item_type: 'Article',
        updated_date: '2022-06-02T07:00:05-04:00',
        created_date: '2022-06-02T07:00:05-04:00',
        published_date: '2022-06-02T07:00:05-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Movies', 'Benediction (Movie)', 'Poetry and Poets'],
        org_facet: [],
        per_facet: ['Davies, Terence', 'Siegrfried Sassoon'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/02/multimedia/02benediction1/02benediction1-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1536,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'Jack Lowden in “Benediction,” a look at the life of the British poet Siegfried Sassoon from the director Terence Davies.',
            copyright: 'Laurence Cendrowicz/Roadside Attractions',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/multimedia/02benediction1/02benediction1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Jack Lowden in “Benediction,” a look at the life of the British poet Siegfried Sassoon from the director Terence Davies.',
            copyright: 'Laurence Cendrowicz/Roadside Attractions',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/multimedia/02benediction1/02benediction1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Jack Lowden in “Benediction,” a look at the life of the British poet Siegfried Sassoon from the director Terence Davies.',
            copyright: 'Laurence Cendrowicz/Roadside Attractions',
          },
        ],
        short_url: 'https://nyti.ms/3m3pZam',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘Watcher’ Review: Terror, at a Glance',
        abstract:
          'In Chloe Okuno’s taut first feature, a woman is convinced a man is watching and possibly even following her.',
        url: 'https://www.nytimes.com/2022/06/02/movies/watcher-review.html',
        uri: 'nyt://article/fbf85f95-4e7e-55e4-8d9c-36014f64a6e7',
        byline: 'By Lena Wilson',
        item_type: 'Article',
        updated_date: '2022-06-02T07:00:03-04:00',
        created_date: '2022-06-02T07:00:03-04:00',
        published_date: '2022-06-02T07:00:03-04:00',
        material_type_facet: '',
        kicker: 'Critic’s Pick',
        des_facet: ['Movies', 'Watcher (Movie)'],
        org_facet: [],
        per_facet: ['Monroe, Maika', 'Okuno, Chloe'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/watcher1/merlin_207643536_82b83b71-79b2-4455-8d3c-e0635d2d944b-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1018,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: 'Maika Monroe in “Watcher.”',
            copyright: 'IFC Midnight',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/watcher1/watcher1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'Maika Monroe in “Watcher.”',
            copyright: 'IFC Midnight',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/watcher1/watcher1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'Maika Monroe in “Watcher.”',
            copyright: 'IFC Midnight',
          },
        ],
        short_url: 'https://nyti.ms/3x9eKDq',
      },
      {
        section: 'business',
        subsection: 'media',
        title: 'Forget Twitter. This Musk Is Into ‘Toe Curling Yumminess.’',
        abstract:
          'Tosca Musk, Elon’s younger sister, is the force behind Passionflix, a streaming service dedicated to adaptations of romance novels and erotic fan fiction.',
        url: 'https://www.nytimes.com/2022/06/02/business/media/tosca-musk-passionflix.html',
        uri: 'nyt://article/86f3f0b0-a4ef-5f63-b541-b686bd5e1046',
        byline: 'By Brooks Barnes',
        item_type: 'Article',
        updated_date: '2022-06-02T09:00:18-04:00',
        created_date: '2022-06-02T09:00:18-04:00',
        published_date: '2022-06-02T09:00:18-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Video Recordings, Downloads and Streaming', 'Women and Girls'],
        org_facet: ['Romance Writers of America'],
        per_facet: ['Musk, Elon', 'Musk, Kimbal', 'Musk, Maye (1948- )', 'Musk, Tosca'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/business/00ToscaMusk-01/00ToscaMusk-01-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 2000,
            width: 1600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Tosca Musk, who runs Passionflix, at a pajama party during the streaming service’s PassionCon last month.',
            copyright: 'Mark Abramson for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/business/00ToscaMusk-01/00ToscaMusk-01-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Tosca Musk, who runs Passionflix, at a pajama party during the streaming service’s PassionCon last month.',
            copyright: 'Mark Abramson for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/business/00ToscaMusk-01/00ToscaMusk-01-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Tosca Musk, who runs Passionflix, at a pajama party during the streaming service’s PassionCon last month.',
            copyright: 'Mark Abramson for The New York Times',
          },
        ],
        short_url: 'https://nyti.ms/3m6U5cZ',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘Interceptor’ Review: Failure to Launch',
        abstract:
          'A soldier defends a missile base in the Pacific nearly single-handedly in this clunky but enthusiastic nuclear thriller.',
        url: 'https://www.nytimes.com/2022/06/02/movies/interceptor-review.html',
        uri: 'nyt://article/ad173805-cdcb-59c8-8d46-37e605fcd97d',
        byline: 'By Nicolas Rapold',
        item_type: 'Article',
        updated_date: '2022-06-02T08:35:23-04:00',
        created_date: '2022-06-02T08:35:23-04:00',
        published_date: '2022-06-02T08:35:23-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Movies', 'Interceptor (Movie)'],
        org_facet: [],
        per_facet: ['Bracey, Luke (1989- )', 'Elsa Pataky', 'Matthew Reilly'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/interceptor1/merlin_207642651_ce12fc79-1c58-4784-9103-1104825078eb-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1365,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: 'Elsa Pataky, right, with Luke Bracey in “Interceptor.”',
            copyright: 'Brook Rushton/Netflix',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/interceptor1/interceptor1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'Elsa Pataky, right, with Luke Bracey in “Interceptor.”',
            copyright: 'Brook Rushton/Netflix',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/interceptor1/interceptor1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'Elsa Pataky, right, with Luke Bracey in “Interceptor.”',
            copyright: 'Brook Rushton/Netflix',
          },
        ],
        short_url: 'https://nyti.ms/3m8FPk0',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘The Score’ Review: Songs in the Key of Heist',
        abstract:
          'The singer-songwriter Johnny Flynn stars alongside Will Poulter and Naomi Ackie in an understated musical about two small-time crooks and a budding romance.',
        url: 'https://www.nytimes.com/2022/06/02/movies/the-score-review.html',
        uri: 'nyt://article/def8c70d-33ff-5d1c-a81b-301beb076d6a',
        byline: 'By Amy Nicholson',
        item_type: 'Article',
        updated_date: '2022-06-02T07:00:10-04:00',
        created_date: '2022-06-02T07:00:10-04:00',
        published_date: '2022-06-02T07:00:10-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Movies', 'The Score (Movie)'],
        org_facet: [],
        per_facet: ['Flynn, Johnny (1983- )', 'Smyth, Malachi', 'Ackie, Naomi', 'Poulter, Will'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/02/multimedia/02score-review/02score-review-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1366,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: 'Johnny Flynn, left, and Will Poulter in “The Score.”',
            copyright: 'Rob Baker Ashton/Gravitas Ventures',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/multimedia/02score-review/02score-review-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'Johnny Flynn, left, and Will Poulter in “The Score.”',
            copyright: 'Rob Baker Ashton/Gravitas Ventures',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/multimedia/02score-review/02score-review-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'Johnny Flynn, left, and Will Poulter in “The Score.”',
            copyright: 'Rob Baker Ashton/Gravitas Ventures',
          },
        ],
        short_url: 'https://nyti.ms/3x9TjCp',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘Freakscene: The Story of Dinosaur Jr.’ Review: A Volatile Band',
        abstract:
          'This alt-rock trio is made up of three soft-spoken guys who generated a big noise, learned to hate one another and then made peace.',
        url: 'https://www.nytimes.com/2022/06/02/movies/freakscene-the-story-of-dinosaur-jr-review.html',
        uri: 'nyt://article/336d4809-5242-5b39-bd66-e8e4a2f3f715',
        byline: 'By Glenn Kenny',
        item_type: 'Article',
        updated_date: '2022-06-02T09:19:39-04:00',
        created_date: '2022-06-02T07:00:08-04:00',
        published_date: '2022-06-02T07:00:08-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: [
          'Documentary Films and Programs',
          'Music',
          'Freakscene: The Story of Dinosaur Jr. (Movie)',
        ],
        org_facet: ['Dinosaur Jr (Music Group)'],
        per_facet: [
          'Philipp Reichenheim',
          'Mascis, Joseph Donald Jr (J Mascis)',
          'Lou Barlow',
          'Murph',
        ],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02freakscene/merlin_207580359_5433e857-59cc-42e2-adc1-dd317cdea239-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1080,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'From left, J Mascis, Lou Barlow and Murph of Dinosaur Jr., in the documentary “Freakscene: The Story of Dinosaur Jr.”',
            copyright: 'Utopia',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02freakscene/02freakscene-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'From left, J Mascis, Lou Barlow and Murph of Dinosaur Jr., in the documentary “Freakscene: The Story of Dinosaur Jr.”',
            copyright: 'Utopia',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/02freakscene/02freakscene-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'From left, J Mascis, Lou Barlow and Murph of Dinosaur Jr., in the documentary “Freakscene: The Story of Dinosaur Jr.”',
            copyright: 'Utopia',
          },
        ],
        short_url: 'https://nyti.ms/3aivcZ2',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘18½’ Review: Watergate, Through a Fog',
        abstract:
          'This political thriller creates a fictional account of a lost Watergate tape by a White House typist.',
        url: 'https://www.nytimes.com/2022/06/02/movies/18-and-a-half-review.html',
        uri: 'nyt://article/2e3678c0-f202-5a0e-8cba-fc250c44348b',
        byline: 'By Teo Bugbee',
        item_type: 'Article',
        updated_date: '2022-06-02T07:00:04-04:00',
        created_date: '2022-06-02T07:00:04-04:00',
        published_date: '2022-06-02T07:00:04-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Movies', '18 (Movie)'],
        org_facet: [],
        per_facet: ['Mirvish, Dan'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/eighteen2/eighteen2-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1152,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: 'John Magaro, left, and Willa Fitzgerald in “18½.”',
            copyright: '18½/Adventure Entertainment',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/eighteen2/eighteen2-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'John Magaro, left, and Willa Fitzgerald in “18½.”',
            copyright: '18½/Adventure Entertainment',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/eighteen2/eighteen2-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'John Magaro, left, and Willa Fitzgerald in “18½.”',
            copyright: '18½/Adventure Entertainment',
          },
        ],
        short_url: 'https://nyti.ms/3m5pFHV',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘Eiffel’ Review: Paris is for Lovers',
        abstract:
          'Gustave Eiffel, the man behind France’s most well-known landmark, is a passionate lover first, and an engineer second in this tedious 19th century romance.',
        url: 'https://www.nytimes.com/2022/06/02/movies/eiffel-review.html',
        uri: 'nyt://article/02c44f8e-65f2-576a-90e4-af1460800adb',
        byline: 'By Beatrice Loayza',
        item_type: 'Article',
        updated_date: '2022-06-02T07:00:03-04:00',
        created_date: '2022-06-02T07:00:03-04:00',
        published_date: '2022-06-02T07:00:03-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Movies', 'Eiffel (Movie)'],
        org_facet: [],
        per_facet: ['Duris, Romain', 'Martin Bourboulon'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/eiffel1/merlin_207641838_430959a4-3395-451e-b095-cd5d78a28f79-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1365,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: 'Emma Mackey and Romain Duris in “Eiffel.”',
            copyright: 'Blue Fox Entertainment',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/eiffel1/eiffel1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'Emma Mackey and Romain Duris in “Eiffel.”',
            copyright: 'Blue Fox Entertainment',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/eiffel1/eiffel1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'Emma Mackey and Romain Duris in “Eiffel.”',
            copyright: 'Blue Fox Entertainment',
          },
        ],
        short_url: 'https://nyti.ms/3M51BzL',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘Maika: The Girl From Another Galaxy’ Review: Boy Meets Alien',
        abstract:
          'This children’s adventure movie from Vietnam is like “E.T.”—but sloppier and more eccentric.',
        url: 'https://www.nytimes.com/2022/06/02/movies/maika-the-girl-from-another-galaxy-review.html',
        uri: 'nyt://article/17a3da4e-8111-51af-b700-05ceac80d1c3',
        byline: 'By Beatrice Loayza',
        item_type: 'Article',
        updated_date: '2022-06-02T07:00:03-04:00',
        created_date: '2022-06-02T07:00:03-04:00',
        published_date: '2022-06-02T07:00:03-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Movies', 'Maika: The Girl From Another Galaxy (Movie)'],
        org_facet: [],
        per_facet: ['Tran, Ham'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/maika1/merlin_207640227_472e46ba-6788-4372-a06a-4717c19ecdfb-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1152,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: 'Diep Anh Chu and Phu Truong Lai in “Maika: The Girl From Another Galaxy.”',
            copyright: 'Well Go USA',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/maika1/maika1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'Diep Anh Chu and Phu Truong Lai in “Maika: The Girl From Another Galaxy.”',
            copyright: 'Well Go USA',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/maika1/maika1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'Diep Anh Chu and Phu Truong Lai in “Maika: The Girl From Another Galaxy.”',
            copyright: 'Well Go USA',
          },
        ],
        short_url: 'https://nyti.ms/3m3q51I',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘Miracle’ Review: A Spiritual Investigation',
        abstract:
          'In this drama set in Romania, when an incident occurs with a novice from a rural convent, a detective seeks answers.',
        url: 'https://www.nytimes.com/2022/06/02/movies/miracle-review.html',
        uri: 'nyt://article/2f862ab0-6a37-5705-9326-49707f530696',
        byline: 'By Ben Kenigsberg',
        item_type: 'Article',
        updated_date: '2022-06-02T07:00:03-04:00',
        created_date: '2022-06-02T07:00:03-04:00',
        published_date: '2022-06-02T07:00:03-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Movies', 'Miracle (Movie)'],
        org_facet: [],
        per_facet: ['Bogdan George Apetri'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/miracle1/miracle1-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1151,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: 'Ioana Bugarin in “Miracle.”',
            copyright: 'Film Movement',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/miracle1/miracle1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'Ioana Bugarin in “Miracle.”',
            copyright: 'Film Movement',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/miracle1/miracle1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'Ioana Bugarin in “Miracle.”',
            copyright: 'Film Movement',
          },
        ],
        short_url: 'https://nyti.ms/3ajRHwH',
      },
      {
        section: 'movies',
        subsection: '',
        title: '‘Hollywood Stargirl’ Review: Starting Anew in La La Land',
        abstract:
          'Julia Hart’s bubbly sequel picks up the story in summertime and reframes around Stargirl, a character who in the first movie was auxiliary by design.',
        url: 'https://www.nytimes.com/2022/06/02/movies/hollywood-stargirl-review.html',
        uri: 'nyt://article/cccec3e1-7cb5-592c-be90-46c292555612',
        byline: 'By Natalia Winkelman',
        item_type: 'Article',
        updated_date: '2022-06-02T07:00:03-04:00',
        created_date: '2022-06-02T07:00:03-04:00',
        published_date: '2022-06-02T07:00:03-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Movies', 'Hollywood Stargirl (Movie)'],
        org_facet: [],
        per_facet: [
          'VanderWaal, Grace',
          'Greer, Judy',
          'Thurman, Uma',
          'Hart, Julia (Film Director)',
        ],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/hollywood1/hollywood1-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1036,
            width: 1844,
            type: 'image',
            subtype: 'photo',
            caption: 'Grace VanderWaal, left, and Elijah Richardson in “Hollywood Stargirl.”',
            copyright: 'Disney+',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/hollywood1/hollywood1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 399,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'Grace VanderWaal, left, and Elijah Richardson in “Hollywood Stargirl.”',
            copyright: 'Disney+',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/01/arts/hollywood1/hollywood1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'Grace VanderWaal, left, and Elijah Richardson in “Hollywood Stargirl.”',
            copyright: 'Disney+',
          },
        ],
        short_url: 'https://nyti.ms/3M90teb',
      },
      {
        section: 'theater',
        subsection: '',
        title: 'Édouard Louis, Miserable in the Spotlight',
        abstract:
          'The French writer played himself onstage and hated the experience, according to a new work he developed with the Swiss director Milo Rau. This time around, there’s an actor in the role.',
        url: 'https://www.nytimes.com/2022/06/02/theater/edouard-louis-the-interrogation.html',
        uri: 'nyt://article/182fd9af-bad2-578d-9e9c-72d9f3b0b7a8',
        byline: 'By Laura Cappelle',
        item_type: 'Article',
        updated_date: '2022-06-02T05:39:34-04:00',
        created_date: '2022-06-02T05:39:34-04:00',
        published_date: '2022-06-02T05:39:34-04:00',
        material_type_facet: '',
        kicker: 'Theater Review',
        des_facet: ['Theater', 'Books and Literature', 'Actors and Actresses'],
        org_facet: ['Theatre de la Colline (Paris, France)'],
        per_facet: ['Louis, Edouard (1992- )', 'Rau, Milo', 'Semenya, Caster'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/02/world/02paristheater-1/merlin_207820590_ad72b396-4dcd-4912-84f5-3f8503e9d17c-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1365,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'Arne De Tremerie as Édouard Louis, kneeling in front of a video screen showing the real Louis, in “The Interrogation,” directed by Milo Rau at the Théâtre de la Colline.',
            copyright: 'Tuong-Vi Nguyen',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/world/02paristheater-1/merlin_207820590_ad72b396-4dcd-4912-84f5-3f8503e9d17c-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Arne De Tremerie as Édouard Louis, kneeling in front of a video screen showing the real Louis, in “The Interrogation,” directed by Milo Rau at the Théâtre de la Colline.',
            copyright: 'Tuong-Vi Nguyen',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/world/02paristheater-1/02paristheater-1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Arne De Tremerie as Édouard Louis, kneeling in front of a video screen showing the real Louis, in “The Interrogation,” directed by Milo Rau at the Théâtre de la Colline.',
            copyright: 'Tuong-Vi Nguyen',
          },
        ],
        short_url: 'https://nyti.ms/3x1UdzE',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'Tips for Summer Living',
        abstract:
          'Advice from an expert about choosing outdoor fabrics, growing bamboo, settling on ceiling fans and finding stylish bird feeders.',
        url: 'https://www.nytimes.com/2022/06/02/arts/design/tips-for-summer-living.html',
        uri: 'nyt://article/b15330e9-7774-527f-9fb5-f18ab92781d1',
        byline: 'By Stephen Treffinger',
        item_type: 'Article',
        updated_date: '2022-06-02T05:02:53-04:00',
        created_date: '2022-06-02T05:02:53-04:00',
        published_date: '2022-06-02T05:02:53-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: [
          'Fans (Airflow)',
          'Content Type: Service',
          'Textiles',
          'Bamboo',
          'Carpets and Rugs',
        ],
        org_facet: [],
        per_facet: [],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-qna-porch/05sp-design-qna-porch-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 2048,
            width: 1275,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Illustrations by Klas Fahl&eacute;n',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-qna-porch/05sp-design-qna-porch-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 401,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Illustrations by Klas Fahl&eacute;n',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-qna-porch/05sp-design-qna-porch-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Illustrations by Klas Fahl&eacute;n',
          },
        ],
        short_url: 'https://nyti.ms/3xa03Ag',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'She Created SZA’s Floral Bikini. Could She Help Me With a Centerpiece?',
        abstract:
          'A reporter learns about flower arranging from a botanical artist who wields a paintbrush.',
        url: 'https://www.nytimes.com/2022/06/02/arts/design/kristen-alpaugh-flower-arranging.html',
        uri: 'nyt://article/c4c9af5d-b392-52e8-b952-a36d71356b14',
        byline: 'By Jane Margolies',
        item_type: 'Article',
        updated_date: '2022-06-02T05:02:53-04:00',
        created_date: '2022-06-02T05:02:53-04:00',
        published_date: '2022-06-02T05:02:53-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Flowers and Plants', 'Orchids', 'Design'],
        org_facet: ['Museum of Arts and Design'],
        per_facet: ['Perry, Katy', 'SZA (Singer)', 'Kristen Alpaugh'],
        geo_facet: ['Los Angeles (Calif)'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-workshop5/merlin_207048777_1b4d1d7c-6c17-407f-95a5-9f6679c90b05-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1365,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'Participants arrange blooms in Kristin Alpaugh’s workshop at the Museum of Arts and Design.',
            copyright: 'Vincent Tullo for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-workshop5/merlin_207048777_1b4d1d7c-6c17-407f-95a5-9f6679c90b05-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Participants arrange blooms in Kristin Alpaugh’s workshop at the Museum of Arts and Design.',
            copyright: 'Vincent Tullo for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-workshop5/05sp-design-workshop5-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Participants arrange blooms in Kristin Alpaugh’s workshop at the Museum of Arts and Design.',
            copyright: 'Vincent Tullo for The New York Times',
          },
        ],
        short_url: 'https://nyti.ms/3GHAB8g',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'Gardens of Earthly Delights',
        abstract:
          'New books on river scavenging, Dumbarton Oaks, eccentric English landscapes and a place called Lotusland.',
        url: 'https://www.nytimes.com/2022/06/02/arts/design/gardens-of-earthly-delights.html',
        uri: 'nyt://article/20c86fa6-f0d2-5d1e-bf0c-a310751ae15e',
        byline: 'By Eve M. Kahn',
        item_type: 'Article',
        updated_date: '2022-06-02T05:02:52-04:00',
        created_date: '2022-06-02T05:02:52-04:00',
        published_date: '2022-06-02T05:02:52-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: [
          'Gardens and Gardening',
          'Flowers and Plants',
          'Books and Literature',
          'Landscaping',
        ],
        org_facet: ['Dumbarton Oaks'],
        per_facet: [],
        geo_facet: ['River Thames (England)', 'Washington (DC)'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-books-mud2/merlin_206813955_8ccf0178-edd2-4aed-9868-c0a9b7846643-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1182,
            width: 1773,
            type: 'image',
            subtype: 'photo',
            caption:
              'In “Mudlark’d: Hidden Histories from the River Thames,” Malcolm Russell writes about the “dopamine hit released by making a find” when scouring the river banks for artifacts. ',
            copyright: 'Matthew Williams-Ellis/Thames & Hudson',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-books-mud2/merlin_206813955_8ccf0178-edd2-4aed-9868-c0a9b7846643-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'In “Mudlark’d: Hidden Histories from the River Thames,” Malcolm Russell writes about the “dopamine hit released by making a find” when scouring the river banks for artifacts. ',
            copyright: 'Matthew Williams-Ellis/Thames & Hudson',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-books-mud2/merlin_206813955_8ccf0178-edd2-4aed-9868-c0a9b7846643-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'In “Mudlark’d: Hidden Histories from the River Thames,” Malcolm Russell writes about the “dopamine hit released by making a find” when scouring the river banks for artifacts. ',
            copyright: 'Matthew Williams-Ellis/Thames & Hudson',
          },
        ],
        short_url: 'https://nyti.ms/3GEZmSA',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'A Panorama of Design',
        abstract: 'Some highlights of Milan Design Week.',
        url: 'https://www.nytimes.com/2022/06/02/arts/design/milan-design-week.html',
        uri: 'nyt://article/a6da3e12-0fa7-5804-8555-0ab5d636ca28',
        byline: '',
        item_type: 'Article',
        updated_date: '2022-06-02T10:11:14-04:00',
        created_date: '2022-06-02T05:00:46-04:00',
        published_date: '2022-06-02T05:00:46-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: [
          'Furniture',
          'Art',
          'Interior Design and Furnishings',
          'Milan Furniture Fair',
          'Design',
          'Conventions, Fairs and Trade Shows',
          'Textiles',
          'Lighting',
        ],
        org_facet: [],
        per_facet: [],
        geo_facet: ['Milan (Italy)'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-pano-lights1/05sp-design-pano-lights1-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1366,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'Andrés Reisinger’s collection of light fixtures, which will be shown at Nilufar Depot during Milan Design Week.',
            copyright: '',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-pano-lights1/05sp-design-pano-lights1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Andrés Reisinger’s collection of light fixtures, which will be shown at Nilufar Depot during Milan Design Week.',
            copyright: '',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-pano-lights1/05sp-design-pano-lights1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Andrés Reisinger’s collection of light fixtures, which will be shown at Nilufar Depot during Milan Design Week.',
            copyright: '',
          },
        ],
        short_url: 'https://nyti.ms/3M9JA3d',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'Beach House, Meet Ocean View',
        abstract:
          'A family’s new home in California was right on the shore, but only a major renovation would make the waves really visible.',
        url: 'https://www.nytimes.com/2022/06/02/arts/design/santa-cruz-beach-house-renovation.html',
        uri: 'nyt://article/f0ebe7d4-d1fe-5d0b-be27-d726776e252a',
        byline: 'By Tim McKeough',
        item_type: 'Article',
        updated_date: '2022-06-02T05:00:37-04:00',
        created_date: '2022-06-02T05:00:37-04:00',
        published_date: '2022-06-02T05:00:37-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Architecture', 'Interior Design and Furnishings'],
        org_facet: ['Fuse Architects', 'Hagen Colbert'],
        per_facet: [],
        geo_facet: ['Watsonville (Calif)', 'Pajaro Dunes'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-santacruz3/merlin_206269443_9ceceb7f-6e13-4246-984a-7f2c90d63b0f-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1530,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'Ben and Rebekah Shaffer’s second home in Watsonville, Calif., which was renovated to maximize ocean views. A glass box containing the dining room now rises higher than the main roof.',
            copyright: 'Joe Fletcher',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-santacruz3/05sp-design-santacruz3-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Ben and Rebekah Shaffer’s second home in Watsonville, Calif., which was renovated to maximize ocean views. A glass box containing the dining room now rises higher than the main roof.',
            copyright: 'Joe Fletcher',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-santacruz3/05sp-design-santacruz3-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Ben and Rebekah Shaffer’s second home in Watsonville, Calif., which was renovated to maximize ocean views. A glass box containing the dining room now rises higher than the main roof.',
            copyright: 'Joe Fletcher',
          },
        ],
        short_url: 'https://nyti.ms/3Mb7Q4T',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'A Southern Home That Embodies Oh-This-Old-Thing Elegance',
        abstract:
          'The Tennessee retreat Keith Meacham shares with her husband and children feels like a love letter to British country estates. And it’s comfortable.',
        url: 'https://www.nytimes.com/2022/06/02/arts/design/keith-meacham-sewanee-home.html',
        uri: 'nyt://article/0dbb0fd5-6b63-5311-a5bd-858e8b8f4e5b',
        byline: 'By Julie Lasky',
        item_type: 'Article',
        updated_date: '2022-06-02T05:00:30-04:00',
        created_date: '2022-06-02T05:00:30-04:00',
        published_date: '2022-06-02T05:00:30-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Interior Design and Furnishings', 'Furniture', 'Tableware', 'Textiles'],
        org_facet: ['Sewanee: The University of the South'],
        per_facet: ['Meacham, Jon', 'Keith Meacham'],
        geo_facet: ['Southern States (US)', 'Tennessee'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-sewanee1/merlin_206871129_fcf9be6d-748a-41eb-927d-5421991f04f8-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1536,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'On the lower-level porch of the Meachams’ Sewanee house, Keith Meacham has laid a table with green glassware on pink paisley.',
            copyright: 'Brinson+Banks for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-sewanee1/05sp-design-sewanee1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'On the lower-level porch of the Meachams’ Sewanee house, Keith Meacham has laid a table with green glassware on pink paisley.',
            copyright: 'Brinson+Banks for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-sewanee1/05sp-design-sewanee1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'On the lower-level porch of the Meachams’ Sewanee house, Keith Meacham has laid a table with green glassware on pink paisley.',
            copyright: 'Brinson+Banks for The New York Times',
          },
        ],
        short_url: 'https://nyti.ms/3GFQc8e',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'A Fresh Start for a Walk in the Park',
        abstract:
          'The Frederik Meijer Gardens & Sculpture Park had a human face long before it received its new welcome center.',
        url: 'https://www.nytimes.com/2022/06/02/arts/design/meijer-gardens-and-sculpture-park-welcome-center.html',
        uri: 'nyt://article/25103537-c2c5-5670-8ce7-b3e560b9a64d',
        byline: 'By Matt Shaw',
        item_type: 'Article',
        updated_date: '2022-06-02T05:00:24-04:00',
        created_date: '2022-06-02T05:00:24-04:00',
        published_date: '2022-06-02T05:00:24-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Sculpture', 'Art', 'Flowers and Plants', 'Architecture'],
        org_facet: [],
        per_facet: ['Tsien, Billie', 'Williams, Tod (Architect)'],
        geo_facet: ['Grand Rapids (Mich)', 'Frederick Meijer Gardens and Sculpture Park'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-meijer1/05sp-design-meijer1-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1366,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'The welcome center for the Meijer Gardens in Grand Rapids, Mich., has been updated by the architects Tod Williams and Billie Tsien.',
            copyright: 'Michael Moran',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-meijer1/05sp-design-meijer1-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'The welcome center for the Meijer Gardens in Grand Rapids, Mich., has been updated by the architects Tod Williams and Billie Tsien.',
            copyright: 'Michael Moran',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-meijer1/05sp-design-meijer1-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'The welcome center for the Meijer Gardens in Grand Rapids, Mich., has been updated by the architects Tod Williams and Billie Tsien.',
            copyright: 'Michael Moran',
          },
        ],
        short_url: 'https://nyti.ms/3N5CqhH',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'Nothing but Flowers (and Some Creatures, Too)',
        abstract: 'A riot of nature-based patterns is bringing fresh life to household goods.',
        url: 'https://www.nytimes.com/2022/06/02/arts/design/floral-pattern-houseware.html',
        uri: 'nyt://article/1c29fa4d-fbf6-5c70-a086-0863909daa99',
        byline: 'By Julie Lasky',
        item_type: 'Article',
        updated_date: '2022-06-02T05:00:21-04:00',
        created_date: '2022-06-02T05:00:21-04:00',
        published_date: '2022-06-02T05:00:21-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Interior Design and Furnishings', 'Textiles', 'Wallpaper', 'Brick and Tile'],
        org_facet: [],
        per_facet: [],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-products-liberty/05sp-design-products-liberty-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1364,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'New outdoor fabrics from Liberty Garden Outdoor Collection; available to the trade only. \nlibertyfabric.com',
            copyright: '',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-products-liberty/05sp-design-products-liberty-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'New outdoor fabrics from Liberty Garden Outdoor Collection; available to the trade only. \nlibertyfabric.com',
            copyright: '',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/05/multimedia/05sp-design-products-liberty/05sp-design-products-liberty-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'New outdoor fabrics from Liberty Garden Outdoor Collection; available to the trade only. \nlibertyfabric.com',
            copyright: '',
          },
        ],
        short_url: 'https://nyti.ms/3afenyg',
      },
      {
        section: 'books',
        subsection: '',
        title: 'Searching for the Past in Cameroon, Only to Find It Is Still Very Present',
        abstract:
          'Patrice Nganang’s trilogy of historical novels explores his country’s national identity, rife with great promise and pain. “The dream of Cameroon is contradictory,” he says.',
        url: 'https://www.nytimes.com/2022/06/02/books/cameroon-nganang.html',
        uri: 'nyt://article/b2a892b7-8a52-5f9c-9204-c5b075ecfe67',
        byline: 'By Anderson Tepper',
        item_type: 'Article',
        updated_date: '2022-06-02T05:00:12-04:00',
        created_date: '2022-06-02T05:00:12-04:00',
        published_date: '2022-06-02T05:00:12-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Content Type: Personal Profile', 'Books and Literature'],
        org_facet: [],
        per_facet: ['Nganang, Patrice (1970- )'],
        geo_facet: ['Cameroon'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/05/18/books/00nganang-image3/merlin_207042162_fede64a6-512b-4887-a744-765cf3df06aa-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 2048,
            width: 1463,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Stacy Kranitz for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/18/books/00nganang-image3/00nganang-image3-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Stacy Kranitz for The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/18/books/00nganang-image3/00nganang-image3-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: '',
            copyright: 'Stacy Kranitz for The New York Times',
          },
        ],
        short_url: 'https://nyti.ms/3M4Ktdr',
      },
      {
        section: 'books',
        subsection: 'review',
        title: 'Guilty Until Proven Innocent: A Gay Refugee’s Confrontation With America',
        abstract:
          'In his memoir, Edafe Okporo calls for a more “humane” treatment of asylum-seekers in the West.',
        url: 'https://www.nytimes.com/2022/06/02/books/review/asylum-edafe-okporo.html',
        uri: 'nyt://article/bf88b5b2-d7a4-53dc-9d17-056e37fd53f5',
        byline: 'By Adaobi Tricia Nwaubani',
        item_type: 'Article',
        updated_date: '2022-06-02T05:00:02-04:00',
        created_date: '2022-06-02T05:00:02-04:00',
        published_date: '2022-06-02T05:00:02-04:00',
        material_type_facet: '',
        kicker: 'Nonfiction',
        des_facet: [
          'Books and Literature',
          'Asylum: A Memoir & Manifesto (Book)',
          'Asylum, Right of',
          'Homosexuality and Bisexuality',
          'Nigerian-Americans',
        ],
        org_facet: [],
        per_facet: ['Okporo, Edafe'],
        geo_facet: ['Nigeria'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/05/20/books/review/00nwaubani-image/merlin_169435740_c6c52012-e3e7-473f-a1ce-37c5e328b7ab-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1324,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'Nigerian men, arrested for public displays of affection toward other men, stand outside the Federal High Court in Lagos, Nigeria, in 2019.',
            copyright: 'Temilade Adelaja/Reuters',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/20/books/review/00nwaubani-image/00nwaubani-image-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Nigerian men, arrested for public displays of affection toward other men, stand outside the Federal High Court in Lagos, Nigeria, in 2019.',
            copyright: 'Temilade Adelaja/Reuters',
          },
          {
            url: 'https://static01.nyt.com/images/2022/05/20/books/review/00nwaubani-image/00nwaubani-image-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Nigerian men, arrested for public displays of affection toward other men, stand outside the Federal High Court in Lagos, Nigeria, in 2019.',
            copyright: 'Temilade Adelaja/Reuters',
          },
        ],
        short_url: 'https://nyti.ms/3m9eyOc',
      },
      {
        section: 'theater',
        subsection: '',
        title: '‘Dreaming Zenzile’ Review: A Tribute to Mama Africa',
        abstract:
          'The musical is Somi Kakoma’s thank-you note, written across generations, to the South African singer and activist Miriam Makeba.',
        url: 'https://www.nytimes.com/2022/06/01/theater/dreaming-zenzile-review.html',
        uri: 'nyt://article/612749b4-de83-58c5-a844-28ae68ed613d',
        byline: 'By Alexis Soloski',
        item_type: 'Article',
        updated_date: '2022-06-01T22:09:27-04:00',
        created_date: '2022-06-01T20:00:06-04:00',
        published_date: '2022-06-01T20:00:06-04:00',
        material_type_facet: '',
        kicker: '',
        des_facet: ['Music', 'Theater', 'Dreaming Zenzile (Play)'],
        org_facet: ['National Black Theater', 'New York Theater Workshop'],
        per_facet: ['Blain-Cruz, Lileana', 'Makeba, Miriam', 'Kakoma, Somi'],
        geo_facet: [],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/01dreaming-zenzile/merlin_207152328_20b07612-d642-43c4-a279-24fbbedea246-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1365,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption: 'Somi Kakoma in the musical “Dreaming Zenzile” at New York Theater Workshop.',
            copyright: 'Sara Krulwich/The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/01dreaming-zenzile/merlin_207152328_20b07612-d642-43c4-a279-24fbbedea246-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption: 'Somi Kakoma in the musical “Dreaming Zenzile” at New York Theater Workshop.',
            copyright: 'Sara Krulwich/The New York Times',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/02/arts/01dreaming-zenzile/01dreaming-zenzile-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption: 'Somi Kakoma in the musical “Dreaming Zenzile” at New York Theater Workshop.',
            copyright: 'Sara Krulwich/The New York Times',
          },
        ],
        short_url: 'https://nyti.ms/3MeLxex',
      },
      {
        section: 'arts',
        subsection: 'design',
        title: 'Louise Bourgeois, Celebrated Sculptor, Unsung Painter',
        abstract:
          'A show at the Metropolitan Museum presents us with what is in many ways a whole new artist whose achievement in painting will need to be factored into art history.',
        url: 'https://www.nytimes.com/2022/06/01/arts/design/louise-bourgeois-paintings.html',
        uri: 'nyt://article/7be11bbc-2391-56a7-b37a-d715d879b424',
        byline: 'By Roberta Smith',
        item_type: 'Article',
        updated_date: '2022-06-02T10:08:44-04:00',
        created_date: '2022-06-01T19:43:00-04:00',
        published_date: '2022-06-01T19:43:00-04:00',
        material_type_facet: '',
        kicker: 'Critic’s Pick',
        des_facet: ['Art'],
        org_facet: ['Metropolitan Museum of Art'],
        per_facet: ['Bourgeois, Louise'],
        geo_facet: ['Paris (France)'],
        multimedia: [
          {
            url: 'https://static01.nyt.com/images/2022/06/03/arts/26bourgeois-review-4/merlin_207208446_54a76833-408c-4236-8588-9f5232cece01-superJumbo.jpg',
            format: 'Super Jumbo',
            height: 1358,
            width: 2048,
            type: 'image',
            subtype: 'photo',
            caption:
              'Louise Bourgeois pictured one of her totemic sculptures in “Roof Song,” 1946-1948, part of a show of her early paintings at the Metropolitan Museum of Art. ',
            copyright: 'Easton Foundation/VAGA at Artists Rights Society (ARS), NY',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/03/arts/26bourgeois-review-4/26bourgeois-review-4-threeByTwoSmallAt2X.jpg',
            format: 'threeByTwoSmallAt2X',
            height: 400,
            width: 600,
            type: 'image',
            subtype: 'photo',
            caption:
              'Louise Bourgeois pictured one of her totemic sculptures in “Roof Song,” 1946-1948, part of a show of her early paintings at the Metropolitan Museum of Art. ',
            copyright: 'Easton Foundation/VAGA at Artists Rights Society (ARS), NY',
          },
          {
            url: 'https://static01.nyt.com/images/2022/06/03/arts/26bourgeois-review-4/26bourgeois-review-4-thumbLarge.jpg',
            format: 'Large Thumbnail',
            height: 150,
            width: 150,
            type: 'image',
            subtype: 'photo',
            caption:
              'Louise Bourgeois pictured one of her totemic sculptures in “Roof Song,” 1946-1948, part of a show of her early paintings at the Metropolitan Museum of Art. ',
            copyright: 'Easton Foundation/VAGA at Artists Rights Society (ARS), NY',
          },
        ],
        short_url: 'https://nyti.ms/3GGCUIK',
      },
    ],
  },
});

copyStateFrom(storiesStore, initialState);
